(()=>{'use strict';const App=window.KartSlot;const FILES={WILD:'wild.png',GOKART:'gokart.png',FLAG:'flag.png',CARD:'card.png',STEERINGWHEEL:'steeringwheel.png',REDLIGHT:'redlight.png',CONE:'cone.png',WRENCH:'wrench.png',BOLTS:'bolts.png',WATERMELON:'watermelon.png',GRAPES:'grapes.png',ORANGE:'orange.png',CHERRY:'cherry.png',WHEEL:'wheel.png'};
class Renderer{
constructor(){this.viewport=document.getElementById('reelViewport');this.reels=[];this.nodes=[[],[],[]];this.current=[['CHERRY','ORANGE','GRAPES'],['WRENCH','BOLTS','WATERMELON'],['CONE','FLAG','GOKART']];this.pool=Object.keys(FILES);this.spinSeeds=[0,0,0];this.stopOverrides=[null,null,null];this.rollingSteps=[null,null,null];this.topCarry=['CARD','CHERRY','ORANGE'];this.imageSources={};this.popUntil=[{}, {}, {}];this.popTimers=[];Object.entries(FILES).forEach(([name,file])=>this.imageSources[name]=App.Config.asset('assets/artwork/'+file));this.refresh();}
static preload(){const paths=['assets/artwork/slot-ui.jpeg','assets/artwork/blankwheel.png',...Object.values(FILES).map(f=>'assets/artwork/'+f)];Renderer.preloaded=Renderer.preloaded||new Map();return Promise.all(paths.map(path=>new Promise(resolve=>{const src=App.Config.asset(path);const img=new Image();img.decoding='sync';img.onload=()=>{const done=()=>{Renderer.preloaded.set(src,img);resolve();};if(img.decode)img.decode().catch(()=>{}).finally(done);else done();};img.onerror=resolve;img.src=src;})));}
applyLayout(){const a=App.Config.get('layout.reelArea');Object.assign(this.viewport.style,{left:a.x+'px',top:a.y+'px',width:a.width+'px',height:a.height+'px',background:a.background||'#090909'});this.gap=+a.gap||0;this.reelWidth=(a.width-this.gap*2)/3;this.rowHeight=a.height/3;this.styleCache={};for(const name of this.pool){const cfg=App.Config.get('layout.symbols.'+name)||{};this.styleCache[name]={scale:(+App.Config.get('layout.symbolScale')||1)*(+cfg.scale||1),offsetX:+cfg.offsetX||0,offsetY:+cfg.offsetY||0,opacity:cfg.opacity??1,rotation:+cfg.rotation||0};}}
build(){this.viewport.innerHTML='';this.reels=[];this.nodes=[[],[],[]];for(let i=0;i<3;i++){const w=document.createElement('div');w.className='reel-window';const an=App.Config.get('layout.anticipation');Object.assign(w.style,{left:(i*(this.reelWidth+this.gap))+'px',width:this.reelWidth+'px',height:(this.rowHeight*3)+'px'});w.style.setProperty('--reel-blur',(+App.Config.get('layout.motion.blur')||0)+'px');w.style.setProperty('--anticipation-border',(+an.borderWidth||7)+'px');w.style.setProperty('--anticipation-inset',(+an.inset||4)+'px');w.style.setProperty('--anticipation-glow',(+an.glowBlur||25)+'px');w.style.setProperty('--anticipation-spread',(+an.glowSpread||6)+'px');w.style.setProperty('--anticipation-opacity',an.opacity??.95);const strip=document.createElement('div');strip.className='reel-strip';w.appendChild(strip);this.viewport.appendChild(w);this.reels.push(w);for(let n=0;n<7;n++){const el=this.createNode();strip.appendChild(el);this.nodes[i].push(el);}this.drawStatic(i,this.current[i]);}}
createNode(){const el=document.createElement('div');el.className='symbol';const img=new Image();img.alt='';img.draggable=false;img.decoding='sync';el.appendChild(img);return el;}
updateNode(el,name,row,reelIndex=-1){const cfg=this.styleCache[name]||{scale:1,offsetX:0,offsetY:0,opacity:1,rotation:0};const snapped=Math.abs(row-Math.round(row))<1e-7?Math.round(row):row;el.hidden=false;el.dataset.symbol=name;el.dataset.row=String(row);const activePop=snapped>=0&&snapped<=2&&(this.popUntil[reelIndex]?.[name]||0)>performance.now();el.classList.toggle('land-pop',!!activePop);if(activePop)el.style.setProperty('--symbol-pop-ms',Math.max(100,+App.Config.get('layout.motion.symbolPopDurationMs')||900)+'ms');Object.assign(el.style,{top:(snapped*this.rowHeight+cfg.offsetY)+'px',width:this.reelWidth+'px',height:this.rowHeight+'px',marginLeft:cfg.offsetX+'px',opacity:cfg.opacity,transform:`translateX(-50%) scale(${cfg.scale}) rotate(${cfg.rotation}deg)`});const img=el.firstElementChild,src=this.imageSources[name]||App.Config.asset('assets/artwork/'+FILES[name]);if(img.src!==new URL(src,document.baseURI).href)img.src=src;img.alt=name;}
hideUnused(i,start){for(let n=start;n<this.nodes[i].length;n++){const el=this.nodes[i][n];el.hidden=true;el.classList.remove('land-pop');}}
strip(i){return this.reels[i].querySelector('.reel-strip');}
drawStatic(i,symbols){const topPeek=Math.max(0.06,Math.min(0.45,+App.Config.get('layout.motion.topRowVisibleFraction')||0.18));this.updateNode(this.nodes[i][0],this.topCarry[i],-(1-topPeek),i);symbols.forEach((s,row)=>this.updateNode(this.nodes[i][row+1],s,row,i));this.hideUnused(i,4);const strip=this.strip(i);strip.style.transform='translate3d(0,0,0)';this.rollingSteps[i]=null;}
beginSpin(i){this.spinSeeds[i]=Math.floor(Math.random()*100000);this.stopOverrides[i]=null;this.rollingSteps[i]=null;this.strip(i).style.transform='translate3d(0,0,0)';}
sequenceSymbol(i,q){const o=this.stopOverrides[i];if(o&&Object.prototype.hasOwnProperty.call(o.map,q))return o.map[q];if(q===-1)return this.topCarry[i];if(q>=0&&q<=2)return this.current[i][q];const n=Math.abs((q*31+this.spinSeeds[i]*17+i*13)%this.pool.length);return this.pool[n];}
renderRolling(i,offset){const strip=this.strip(i),u=offset/this.rowHeight,step=Math.floor(u);strip.style.transform='translate3d(0,0,0)';let n=0;for(let q=-step-2;q<=-step+4;q++,n++)this.updateNode(this.nodes[i][n],this.sequenceSymbol(i,q),q+u,i);this.hideUnused(i,n);this.rollingSteps[i]=step;}
prepareStop(i,target,startOffset){const finalSteps=Math.ceil(startOffset/this.rowHeight)+3,finalOffset=finalSteps*this.rowHeight,map={};const top=this.sequenceSymbol(i,-finalSteps-1);map[-finalSteps-1]=top;for(let row=0;row<3;row++)map[-finalSteps+row]=target[row];this.stopOverrides[i]={map,finalOffset,topSymbol:top};this.rollingSteps[i]=null;return finalOffset;}
settle(i,target,m){return new Promise(resolve=>{this.current[i]=target.slice();this.rollingSteps[i]=null;if(this.stopOverrides[i]?.topSymbol)this.topCarry[i]=this.stopOverrides[i].topSymbol;const strip=this.strip(i),amount=this.rowHeight*(+m.rebound||0);strip.getAnimations().forEach(a=>a.cancel());strip.style.transform='translate3d(0,0,0)';if(Math.abs(amount)<.01){this.drawStatic(i,target);setTimeout(resolve,+m.settlePauseMs||0);return;}const anim=strip.animate([{transform:`translate3d(0,${-amount}px,0)`},{transform:'translate3d(0,0,0)'}],{duration:(+m.bounceOutMs||0)+(+m.bounceBackMs||0),easing:'cubic-bezier(.18,.84,1,1)',fill:'both'});anim.finished.then(()=>{anim.cancel();strip.style.transform='translate3d(0,0,0)';this.drawStatic(i,target);setTimeout(resolve,+m.settlePauseMs||0);});});}
popLanded(index,names=['WHEEL','CARD']){const strip=this.strip(index),duration=Math.max(100,+App.Config.get('layout.motion.symbolPopDurationMs')||900),until=performance.now()+duration;names.forEach(name=>{this.popUntil[index][name]=until;strip.querySelectorAll(`.symbol[data-symbol="${name}"]`).forEach(el=>{const row=parseFloat(el.dataset.row||'-99');if(row<-.05||row>2.05)return;el.classList.remove('land-pop');void el.offsetWidth;el.style.setProperty('--symbol-pop-ms',duration+'ms');el.classList.add('land-pop');});});clearTimeout(this.popTimers[index]);this.popTimers[index]=setTimeout(()=>{names.forEach(name=>{delete this.popUntil[index][name];strip.querySelectorAll(`.symbol[data-symbol="${name}"]`).forEach(el=>el.classList.remove('land-pop'));});},duration+40);}
setAnticipation(index,on){this.reels[index]?.classList.toggle('anticipating',!!on);}refresh(){this.applyLayout();this.build();}getCurrent(){return this.current.map(r=>r.slice());}}
App.Renderer=Renderer;App.SymbolFiles=FILES;})();
